[WIP] Dockerized testing
Rippling/cloudlift pull request #20
Opened 2020-07-19 19:02 UTC by siliconsenthil

2020-08-26 14:12 UTC, aswinkarthik commented on Jenkinsfile
> +                    git push --tags
can we push the tag we create? `push --tags` is to push all tags. Even though there is only one tag to push, i feel it is better to just explicitely just push our tag. What is your opinion?

2020-08-26 14:13 UTC, aswinkarthik requested changes

2020-08-26 14:13 UTC, aswinkarthik commented on Jenkinsfile
> +                    aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 408750594584.dkr.ecr.us-west-2.amazonaws.com
Shall we configure REGION and ACCOUNT_ID in jenkins as well? We can just use them as env variable here?

2020-08-26 15:04 UTC, bkdonline commented on Jenkinsfile
> +                    git push --tags
Agreed. Fixed.

2020-08-26 15:04 UTC, bkdonline commented on Jenkinsfile
> +                    aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 408750594584.dkr.ecr.us-west-2.amazonaws.com
<img width="452" alt="image" src="https://user-images.githubusercontent.com/12269108/91320734-7ed58d00-e7db-11ea-87c2-201d410d8eec.png">
Makes sense. Fixed.

2020-08-27 10:11 UTC, aswinkarthik approved these changes

2020-08-27 10:13 UTC, merged