Add ability to set scaling policy
Rippling/cloudlift pull request #34
Opened 2020-08-19 05:50 UTC by aswinkarthik

2020-08-19 12:54 UTC, siliconsenthil approved these changes

2020-09-18 15:04 UTC, siliconsenthil requested changes
Let's have a conversation on these comments, please

2020-09-18 15:04 UTC, siliconsenthil commented on cloudlift/deployment/service_template_generator.py
> +                        alb if create_new_alb else config['http_interface']['alb'],
Can we pull the ALB object and send instead of passing string and object in same variable?

2020-10-19 06:26 UTC, sannithibalaji commented on cloudlift/deployment/deployer.py
> +                                scalable_target_min_count)) if scalable_target_min_count else deployment.service.desired_count
yes, doing it.

2020-10-19 08:25 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +        from troposphere.applicationautoscaling import ScalingPolicy, TargetTrackingScalingPolicyConfiguration, \
done

2020-10-19 08:40 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +                                        Description="Minimum number of task to maintain",
remove it, as it's unnecessary

2020-10-19 08:40 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +        from troposphere.applicationautoscaling import ScalableTarget
done

2020-10-19 08:40 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +    def _get_desired_task_count_for_service(self, service_name, min_count=0):
changed

2020-10-19 08:40 UTC, sannithibalaji commented on README.md
> +Supported autoscaling policies `request_count_per_target`. It works only if there is a `http_interface`
we can use it for both http_interface, udp_interface, as well as for things without any load balancer as well (eg ETA).

2020-10-19 11:52 UTC, sannithibalaji approved these changes

2020-10-19 12:29 UTC, siliconsenthil requested changes

2020-10-19 12:29 UTC, siliconsenthil commented on cloudlift/config/service_configuration.py
> +                "autoscaling": {
Let's mandate all the properties in autoscaling

2020-10-19 12:29 UTC, siliconsenthil commented on cloudlift/deployment/service_template_generator.py
> +
Remove this empty space

2020-10-19 12:29 UTC, siliconsenthil commented on cloudlift/deployment/service_template_generator.py
> +    def __add_scalable_target(self, ecs_svc, config):
We are following single `_` prefix for private methods no?

2020-10-19 12:29 UTC, siliconsenthil commented on cloudlift/deployment/service_template_generator.py
> +                if 'request_count_per_target' in autoscaling_config:
We should mandate `request_count_per_target` in autoscaling config and remove this condition

2020-10-19 12:29 UTC, siliconsenthil commented on cloudlift/deployment/service_template_generator.py
> +
We have two cases based on type of `alb`. Are both covered in tests?

2020-10-20 07:56 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +                if 'request_count_per_target' in autoscaling_config:
done

2020-10-20 07:56 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +    def __add_scalable_target(self, ecs_svc, config):
done

2020-10-20 07:56 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +
done

2020-10-20 07:57 UTC, sannithibalaji commented on cloudlift/config/service_configuration.py
> +                "autoscaling": {
done

2020-10-20 08:16 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +
thanks for pointing this out, saw that we don't pass alb arn in config, and alb alarms which is most important are not getting created because of them. fixing all of them.

2020-10-20 12:47 UTC, sannithibalaji commented on cloudlift/deployment/service_template_generator.py
> +
it's fixed now. we have test case for both types of alb. new alb as well as existing alb

2020-10-20 13:15 UTC, siliconsenthil approved these changes

2020-10-20 13:44 UTC, merged