Secrets manager support
Rippling/cloudlift pull request #40
Opened 2020-09-04 18:57 UTC by siliconsenthil

2020-09-06 17:39 UTC, siliconsenthil commented on cloudlift/deployment/service_information_fetcher.py
> -    def log_ips(self):
Dead code removal

2020-09-06 17:39 UTC, siliconsenthil commented on cloudlift/deployment/service_information_fetcher.py
> -        self.ecs_client = get_client_for('ecs', self.environment)
Refactor: Moved them as local variables where needed. Makes testing easier and code lighter

2020-09-06 17:41 UTC, siliconsenthil commented on cloudlift/deployment/service_template_generator.py
> +            self.template.add_output(Output(service_name + "SecretsNamePrefix",
Adding secret name prefix as an output to be used during deployment. The cfn output is preferred as it reflects the true state of the stack. The dynamoDB config can be outdated as there can be  failure between dynamoDB update and cfn apply

2020-09-06 17:43 UTC, siliconsenthil commented on cloudlift/deployment/service_template_generator.py
> +        secrets_arn_regex = f"arn:aws:secretsmanager:{self.region}:{self.account_id}:secret:*-{self.env}-??????"
taskExecutionRole is [needed](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html) to pull secrets when the container is started.

2020-09-06 17:44 UTC, siliconsenthil commented on cloudlift/deployment/service_updater.py
> -        self.init_stack_info()
The same logic was present in `ServiceInformationFetcher`. So removed that logic here and reusing ServiceInformationFetcher

2020-09-06 17:45 UTC, siliconsenthil commented on test/test_cloudlift.py
> +TEST_DIR = Path(__file__).resolve().parent
Using pathlib to avoid the dependency of the test being run from specific dir

2020-09-07 06:01 UTC, aswinkarthik requested changes

2020-09-08 10:31 UTC, aswinkarthik approved these changes

2020-09-08 10:35 UTC, merged