Assign random available priority to listener rule
Rippling/cloudlift pull request #82
Opened 2020-11-18 14:00 UTC by Equlnox

2020-11-19 09:06 UTC, aswinkarthik requested changes

2020-11-19 09:06 UTC, aswinkarthik commented on cloudlift/config/service_configuration.py
> +            if reuse_existing_alb and 'priority' not in config['http_interface']['alb']['priority']:
This seems wrong. 
```
'priority' not in config['http_interface']['alb']['priority']:
```
Should it be

```
'priority' not in config['http_interface']['alb']:
```

can you add a unit tests for this?

2020-11-19 09:06 UTC, aswinkarthik commented on cloudlift/config/service_configuration.py
> +            return -1
shall we raise Exception here instead?

2020-11-19 09:06 UTC, aswinkarthik commented on cloudlift/deployment/service_information_fetcher.py
> +        return next((rule for rule in self.listener_rules if rule['LogicalResourceId'].beginswith(service_name)), None)
Would `next` error out if self.listener_rules is empty list?

2020-11-19 09:29 UTC, Equlnox commented on cloudlift/deployment/service_information_fetcher.py
> +        return next((rule for rule in self.listener_rules if rule['LogicalResourceId'].beginswith(service_name)), None)
It would return `None`

2020-11-19 10:27 UTC, Equlnox commented on cloudlift/config/service_configuration.py
> +            return -1
Raising exception now

2020-11-20 05:56 UTC, aswinkarthik approved these changes

2020-11-20 13:25 UTC, merged