Hard limit of memory
Rippling/cloudlift pull request #93
Opened 2020-12-29 14:30 UTC by sannithibalaji

2020-12-29 14:45 UTC, siliconsenthil requested changes

2020-12-29 14:45 UTC, siliconsenthil commented on cloudlift/deployment/deployer.py
> +        task_definition.apply_memory_hard_limit(20480)
Make this into a constant named `HARD_LIMIT_MEMORY_IN_MIB`

2020-12-29 14:48 UTC, sannithibalaji commented on cloudlift/deployment/deployer.py
> +        task_definition.apply_memory_hard_limit(20480)
sure, updated it.

2020-12-30 13:30 UTC, siliconsenthil approved these changes

2020-12-30 13:31 UTC, merged