developer owned config
Rippling/cloudlift pull request #95
Opened 2021-01-05 00:24 UTC by sannithibalaji

2021-01-05 09:09 UTC, sannithibalaji commented on test/dummy/load_secrets_from_env.py
> +    subprocess.check_output(sys.argv[1:])
@aswinkarthik I need your help here. currently, it's is creating a new process. is there any way to get it in the same process?

2021-01-05 09:41 UTC, siliconsenthil commented on test/dummy/load_secrets_from_env.py
> +    subprocess.check_output(sys.argv[1:])
@sannithibalaji You can parse the `INJECTED_VAR_` in python and let it return a string in env format. That you can eval inside the `run-server.sh` script. The problem is that we need to do that in all startup scripts. The other way is to do this inside application. But that will break local running.

2021-01-05 15:00 UTC, aswinkarthik commented on test/dummy/load_secrets_from_env.py
> +    subprocess.check_output(sys.argv[1:])
Yeah the python script should literally print contents like

```bash
export LABEL="a"
export PORT=8080
```

Entry point should not be a python file. It should be a shell script that should

```bash
eval $(python ./script.py)
exec $@
```

2021-01-05 15:12 UTC, aswinkarthik requested changes

2021-01-05 15:12 UTC, aswinkarthik commented on cloudlift/deployment/deployer.py
> +    files_in_directory = list(os.walk(directory_path))[0][2]
Generally `walk` is to traverse directory structures from top down/bottom up. 
What we are lookking for is specific patterns of files.
Its better if we use [glob](https://docs.python.org/3/library/glob.html) here

2021-01-05 15:12 UTC, aswinkarthik commented on cloudlift/deployment/deployer.py
> +    namespaces = get_exec_namespaces(sample_env_folder_path)
Seems to be a redundant `get_exec_namespaces` call. We can just pass the `namespaces` again from `build_config`

2021-01-05 15:14 UTC, aswinkarthik commented on cloudlift/deployment/deployer.py
> +def get_secret_name(secret_name_prefix, env_name, name_space):
Purely for consistency, shall we just call `namespace` and `namespaces` instead of `name_space`?

2021-01-05 15:29 UTC, aswinkarthik requested changes

2021-01-05 15:29 UTC, aswinkarthik commented on cloudlift/deployment/deployer.py
> +def find_duplicate_keys(directory_path, namespaces):
This logic seems to cross check across all env.sample files. Its better to just intersect all `get_sample_keys` results and return the result

2021-01-05 15:29 UTC, aswinkarthik commented on cloudlift/deployment/deployer.py
> +    _validate_config_availability(sample_config_keys,
`_validate_config_availability` is validating `sample_config_keys` again. Hasnt this already happened in `get_secrets_for_all_namespaces`? Also i think this would fail. `env.sample` is being tested against union of everything.

2021-01-11 14:09 UTC, aswinkarthik approved these changes

2021-01-12 05:11 UTC, merged